#cloud-config
package_upgrade: true
packages:
  - nginx
write_files:
  - owner: www-data:www-data
    path: /etc/nginx/sites-available/default
    defer: true
    content: |
      server {
        listen 443 ssl http2;
        client_max_body_size 1G;
        server_tokens off;
        keepalive_timeout   70;
        proxy_hide_header X-Powered-By;
        server_name az-opro-nonprod.kai-oscar.com;
        ssl_certificate /etc/nginx/ssl/certificates.pem;
        ssl_certificate_key /etc/nginx/ssl/certificates.key;
        ssl_dhparam /etc/nginx/ssl/dhparam.pem;
        ssl_session_timeout 10m;
        ssl_session_cache shared:SSL:10m;
        ssl_protocols TLSv1.2;
        ssl_ciphers "ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:!aNULL:!eNULL:!EXPORT:!DSS:!DES:!RC4:!3DES:!MD5:!PSK";
        ssl_prefer_server_ciphers on;
        ssl_stapling on;
        ssl_stapling_verify on;
        ssl_trusted_certificate /etc/nginx/ssl/certificates.pem;

        resolver 10.48.128.4 10.48.128.5 valid=15s;
        resolver_timeout 10s;

        location / {
          proxy_redirect          off;
          set $backend_host c1005554548-s0.private-nonprod.oscar.com;
          proxy_pass              https://$backend_host;
          proxy_set_header        Host $host;
          proxy_set_header        X-Forwarded-Proto $scheme;
          proxy_set_header        X-Forwarded-For   $proxy_add_x_forwarded_for;
          proxy_set_header        X-Real-IP         $remote_addr;
          proxy_read_timeout      60;
        }
        location = / {
          return 301 /oscar/;
        }
      }
runcmd:
  - apt -y autoremove
  - mkdir -p /etc/nginx/ssl
  - openssl req -x509 -newkey rsa:4096 -keyout /etc/nginx/ssl/certificates.key -out /etc/nginx/ssl/certificates.pem -sha256 -days 3650 -nodes -subj "/C=CA/O=WellHealth/CN=well.local"
  - openssl dhparam -out /etc/nginx/ssl/dhparam.pem 4096
  - resolvectl domain eth0 well.local well.company
  - service systemd-resolved restart
  - service nginx restart
